//     if(function_exists('register_field_group'))
        //     {
        //         // OUR ACF GOODIES ARE GOING TO GO HERE
        //         if( function_exists('acf_add_local_field_group') ):

        //             acf_add_local_field_group(array (
        //                 'key' => 'group_5845003950def',
        //                 'title' => 'TW Weather',
        //                 'fields' => array (
        //                     array (
        //                         'sub_fields' => array (
        //                             array (
        //                                 'return_format' => 'url',
        //                                 'preview_size' => 'thumbnail',
        //                                 'library' => 'all',
        //                                 'min_width' => 1057,
        //                                 'min_height' => 403,
        //                                 'min_size' => '',
        //                                 'max_width' => 1057,
        //                                 'max_height' => 403,
        //                                 'max_size' => '',
        //                                 'mime_types' => '',
        //                                 'key' => 'field_5845a0ae45ddb',
        //                                 'label' => 'Default Image',
        //                                 'name' => 'default_image',
        //                                 'type' => 'image',
        //                                 'instructions' => 'Upload an image that is exactly 1057px by 403px. This is the image that will appear if there is an error retrieving current weather conditions.',
        //                                 'required' => 0,
        //                                 'conditional_logic' => 0,
        //                                 'wrapper' => array (
        //                                     'width' => '',
        //                                     'class' => '',
        //                                     'id' => '',
        //                                 ),
        //                             ),
        //                             array (
        //                                 'return_format' => 'url',
        //                                 'preview_size' => 'thumbnail',
        //                                 'library' => 'all',
        //                                 'min_width' => 1057,
        //                                 'min_height' => 403,
        //                                 'min_size' => '',
        //                                 'max_width' => 1057,
        //                                 'max_height' => 403,
        //                                 'max_size' => '',
        //                                 'mime_types' => '',
        //                                 'key' => 'field_5845a1261014a',
        //                                 'label' => 'Rainy Image',
        //                                 'name' => 'rainy_image',
        //                                 'type' => 'image',
        //                                 'instructions' => 'Upload an image that is exactly 1057px by 403px.',
        //                                 'required' => 0,
        //                                 'conditional_logic' => 0,
        //                                 'wrapper' => array (
        //                                     'width' => '',
        //                                     'class' => '',
        //                                     'id' => '',
        //                                 ),
        //                             ),
        //                             array (
        //                                 'return_format' => 'url',
        //                                 'preview_size' => 'thumbnail',
        //                                 'library' => 'all',
        //                                 'min_width' => 1057,
        //                                 'min_height' => 403,
        //                                 'min_size' => '',
        //                                 'max_width' => 1057,
        //                                 'max_height' => 403,
        //                                 'max_size' => '',
        //                                 'mime_types' => '',
        //                                 'key' => 'field_5845a187b2581',
        //                                 'label' => 'Foggy Image',
        //                                 'name' => 'foggy_image',
        //                                 'type' => 'image',
        //                                 'instructions' => 'Upload an image that is exactly 1057px by 403px.',
        //                                 'required' => 0,
        //                                 'conditional_logic' => 0,
        //                                 'wrapper' => array (
        //                                     'width' => '',
        //                                     'class' => '',
        //                                     'id' => '',
        //                                 ),
        //                             ),
        //                             array (
        //                                 'return_format' => 'url',
        //                                 'preview_size' => 'thumbnail',
        //                                 'library' => 'all',
        //                                 'min_width' => 1057,
        //                                 'min_height' => 403,
        //                                 'min_size' => '',
        //                                 'max_width' => 1057,
        //                                 'max_height' => 403,
        //                                 'max_size' => '',
        //                                 'mime_types' => '',
        //                                 'key' => 'field_5845a19bb2582',
        //                                 'label' => 'Sunny Image',
        //                                 'name' => 'sunny_image',
        //                                 'type' => 'image',
        //                                 'instructions' => 'Upload an image that is exactly 1057px by 403px.',
        //                                 'required' => 0,
        //                                 'conditional_logic' => 0,
        //                                 'wrapper' => array (
        //                                     'width' => '',
        //                                     'class' => '',
        //                                     'id' => '',
        //                                 ),
        //                             ),
        //                             array (
        //                                 'return_format' => 'url',
        //                                 'preview_size' => 'thumbnail',
        //                                 'library' => 'all',
        //                                 'min_width' => 1057,
        //                                 'min_height' => 403,
        //                                 'min_size' => '',
        //                                 'max_width' => 1057,
        //                                 'max_height' => 403,
        //                                 'max_size' => '',
        //                                 'mime_types' => '',
        //                                 'key' => 'field_5845a1bfb2583',
        //                                 'label' => 'Windy Image',
        //                                 'name' => 'windy_image',
        //                                 'type' => 'image',
        //                                 'instructions' => 'Upload an image that is exactly 1057px by 403px.',
        //                                 'required' => 0,
        //                                 'conditional_logic' => 0,
        //                                 'wrapper' => array (
        //                                     'width' => '',
        //                                     'class' => '',
        //                                     'id' => '',
        //                                 ),
        //                             ),
        //                             array (
        //                                 'return_format' => 'url',
        //                                 'preview_size' => 'thumbnail',
        //                                 'library' => 'all',
        //                                 'min_width' => 1057,
        //                                 'min_height' => 403,
        //                                 'min_size' => '',
        //                                 'max_width' => 1057,
        //                                 'max_height' => 403,
        //                                 'max_size' => '',
        //                                 'mime_types' => '',
        //                                 'key' => 'field_5845a1eeb2585',
        //                                 'label' => 'Snowy Image',
        //                                 'name' => 'snowy_image',
        //                                 'type' => 'image',
        //                                 'instructions' => 'Upload an image that is exactly 1057px by 403px.',
        //                                 'required' => 0,
        //                                 'conditional_logic' => 0,
        //                                 'wrapper' => array (
        //                                     'width' => '',
        //                                     'class' => '',
        //                                     'id' => '',
        //                                 ),
        //                             ),
        //                         ),
        //                         'min' => 0,
        //                         'max' => 0,
        //                         'layout' => 'row',
        //                         'button_label' => '',
        //                         'collapsed' => 'field_584500d224db2',
        //                         'key' => 'field_5845007d24db1',
        //                         'label' => 'TW Weather Header Images',
        //                         'name' => 'tw_weather_header_images',
        //                         'type' => 'repeater',
        //                         'instructions' => 'Add header images for Foggy, Rainy, Hazy, Cloudy and Sunny conditions',
        //                         'required' => 0,
        //                         'conditional_logic' => 0,
        //                         'wrapper' => array (
        //                             'width' => '',
        //                             'class' => '',
        //                             'id' => '',
        //                         ),
        //                     ),
        //                 ),
        //                 'location' => array (
        //                     array (
        //                         array (
        //                             'param' => 'options_page',
        //                             'operator' => '==',
        //                             'value' => 'tw_plugin_options',
        //                         ),
        //                     ),
        //                 ),
        //                 'menu_order' => 0,
        //                 'position' => 'acf_after_title',
        //                 'style' => 'default',
        //                 'label_placement' => 'top',
        //                 'instruction_placement' => 'label',
        //                 'hide_on_screen' => '',
        //                 'active' => 1,
        //                 'description' => '',
        //             ));

        //             endif;
            // }